[package]
name = "wars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portal-pc-waffle.workspace = true
proc-macro2 = "1.0.85"
quote = "1.0.36"
relooper = "0.1.0"
syn = "2.0.66"

